Add entity User
AliKamil/tnews-subscription-service pull request #2
Opened 2024-11-22 21:25 UTC by monkey-keeper

2024-11-24 14:31 UTC, SHVERR commented on .idea/.gitignore
Я бы дополнил этот файл исключениями, так как много лишнего грузится из локального проекта.

2024-11-24 19:34 UTC, SHVERR commented on build.gradle.kts
> +    compileOnly("org.projectlombok:lombok:1.18.36")
Тут мне пришлось добавить ещё зависимость

annotationProcessor("org.projectlombok:lombok:1.18.36")
 
Без неё аннотации ломбок не работали и проект не компилировался

2024-11-25 12:29 UTC, AliKamil requested changes

2024-11-25 12:29 UTC, AliKamil commented on .gradle/8.11-rc-1/checksums/checksums.lock
./gradle тоже уходит в игнор, это информация о твоем билде.

2024-11-25 12:29 UTC, AliKamil commented on build/classes/java/main/tnews/Application.class
.build папка тоже не коммитится, там результат работы  сборщика. 

Вот такой .ignore будет хорошим: 

```
# Gradle
.gradle/
build/
!build.gradle
!settings.gradle
!gradle-wrapper.jar
!gradle-wrapper.properties

# Eclipse project files
.project
.classpath
.settings/

# IntelliJ IDEA project files
.idea/
*.iml
*.iws

# NetBeans project files
nbproject/

# Maven wrapper files
.mvn/
target/

# Logs
*.log

# OS generated files - if you use MacOS
.DS_Store
Thumbs.db

# Gradle cache
.gradle/

# Dependency directories
/.m2/
/node_modules/

# Spring Boot specific
spring-boot-devtools.properties

```

2024-11-25 12:29 UTC, AliKamil commented on settings.gradle.kts
rootProject.name должен быть названием проекта все-таки.

2024-11-25 12:29 UTC, AliKamil commented on src/main/java/tnews/entity/User.java
> +    private Subscription subscription;
К вопросу о связи между подпиской и пользователем - 1 к 1 или один ко многим?

2024-11-26 17:27 UTC, AliKamil approved these changes

2024-11-26 17:29 UTC, merged